---
  title: "Exploratory"
author: "Kevin Hu"
output:
  pdf_document:
  toc: yes
toc_depth: 3
html_document:
  df_print: paged
toc: yes
toc_float:
  collapsed: no
word_document: default
editor_options:
  chunk_output_type: inline
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(error=TRUE, fig.height=8, fig.width=12, warning = F, message = F, cache = TRUE)
```

```{r}
library(GGally)
library(ggplot2)
library(RColorBrewer)
require(plyr)

```

# Load CSV

```{r}
pokemons_df <- read.csv("../data/processed/pokemons.csv")
pokemons_df$legendary <- mapvalues(pokemons_df$is_legendary, 
          from=c(TRUE,FALSE), 
          to=c("Legendary","Normal"))

pokemons_df$log_height <- log10(pokemons_df$height)
pokemons_df$log_weight <- log10(pokemons_df$weight)

head(pokemons_df)
```

# Stats by type

```{r}
plot_by_primary <- function(var,var_name){
  colourCount = length(unique(pokemons_df$type_primary))
  getPalette = colorRampPalette(brewer.pal(9, "Set3"))
  
  bymedian <- reorder(pokemons_df$type_primary, pokemons_df[,var], median)
  
  plt <- ggplot(pokemons_df, aes_string(x=bymedian, y=var, fill="type_primary")) + 
    geom_violin(trim=FALSE)+
    geom_boxplot(width=0.1, fill="white")+
    labs(title=paste(var_name,"by primary type"),x="Primary type", y = var_name) +
    scale_fill_manual(values = getPalette(colourCount)) +
    theme_classic() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),legend.position = "none")
  
  return(plt)
}
```

## Base experience

```{r}
plot_by_primary("base_experience","Base experience")
ggsave("../plots/base_experience_by_primary_type.pdf",scale=0.5)
```

## Height
```{r}
plt <- plot_by_primary("height","Height")
plt + scale_y_continuous(trans='log10')
ggsave("../plots/height_by_primary_type.pdf",scale=0.5)
```

## Weight

```{r}
plt <- plot_by_primary("weight","Weight")
plt + scale_y_continuous(trans='log10')
ggsave("../plots/weight_by_primary_type.pdf",scale=0.5)
```

```{r}
plot_by_primary("speed_base","Speed")
ggsave("../plots/speed_by_primary_type.pdf",scale=0.5)
```

```{r}
plot_by_primary("defense_base","Defense")
ggsave("../plots/defense_by_primary_type.pdf",scale=0.5)
```

```{r}
plot_by_primary("attack_base","Attack")
ggsave("../plots/attack_by_primary_type.pdf",scale=0.5)
```

```{r}
plot_by_primary("hp_base","HP")
ggsave("../plots/hp_by_primary_type.pdf",scale=0.5)
```

# Bunch of boxplots

```{r}

library(gridExtra)

p <- list()

select_vars = c("log_height","log_weight", "base_experience","speed_base","defense_base","special.defense_base","attack_base","special.attack_base", "hp_base")
select_names = c("Height (log10)","Weight (log10)", "Experience","Speed", "Defense","Defense (special)", "Attack","Attack (special)", "HP")

order <- factor(pokemons_df$legendary,levels=c("Normal","Legendary"))

for (i in 1:length(select_vars)) {
  
  var <- select_vars[i]
  name <- select_names[i]
  
  p[[i]] <- ggplot(data=pokemons_df, aes_string(x=order, y=var)) +
            geom_boxplot(aes(fill=order),notch=TRUE) + guides(fill=FALSE) + 
            theme(axis.title.y = element_text(size=14)) +
            xlab("") + ylab(name) + 
            theme_classic() + 
            scale_fill_manual(values=c("#eaeaea", "#a8d8ea"))
}

plots <- do.call(grid.arrange, c(p, ncol=3))

ggsave("../plots/legendary_boxplots.pdf",plots,width=8,height=6)
```

# Correlations between everything

```{r}
corrs <- ggpairs(pokemons_df, mapping = aes(color = legendary), 
                      columns = c("base_experience","log_height","log_weight","speed_base","defense_base","attack_base","hp_base"), 
                      columnLabels = c("Base experience","Height (log10)","Weight (log10)","Speed","Defense","Attack","HP"),
                 method="spearman"
                 )

corrs <- corrs + theme_minimal()
ggsave("../plots/correlation_pairs.pdf",corrs,scale=0.5)
```


```{r}
pdf('../plots/qqplots.pdf', width=10, height=5)

par(mfrow=c(2,4))

qqnorm(pokemons_df$height, pch = 1, frame = FALSE,main="Height")
qqline(pokemons_df$height, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$weight, pch = 1, frame = FALSE,main="Weight")
qqline(pokemons_df$weight, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$speed_base, pch = 1, frame = FALSE,main="Speed")
qqline(pokemons_df$speed_base, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$defense_base, pch = 1, frame = FALSE,main="Defense")
qqline(pokemons_df$defense_base, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$log_height, pch = 1, frame = FALSE,main="Height (log10)")
qqline(pokemons_df$log_height, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$log_weight, pch = 1, frame = FALSE,main="Weight (log10)")
qqline(pokemons_df$log_weight, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$attack_base, pch = 1, frame = FALSE,main="Attack")
qqline(pokemons_df$attack_base, col = "steelblue", lwd = 2)

qqnorm(pokemons_df$hp_base, pch = 1, frame = FALSE,main="HP")
qqline(pokemons_df$hp_base, col = "steelblue", lwd = 2)

dev.off()
```